productos = [
    'acai',
    'ackee',
    'apple',
    'apricot',
    'avocado',
    'banana',
    'bilberry',
    'blackberry',
    'blackcurrant',
    'black',
    'blueberry',
    'boysenberry',
    'breadfruit',
    'buddha',
    'cactus',
    'crab',
    'currant',
    'cherry',
    'cherimoya',
    'chico',
    'cloudberry',
    'coconut',
    'cranberry',
    'damson',
    'date',
    'dragonfruit',
    'durian',
    'elderberry',
    'feijoa',
    'fig',
    'goji',
    'gooseberry',
    'grape',
    'grewia',
    'raisin',
    'grapefruit',
    'guava',
    'hala',
    'honeyberry',
    'huckleberry',
    'jabuticaba',
    'jackfruit',
    'jambul',
    'japanese',
    'jostaberry',
    'jujube',
    'juniper',
    'kiwano',
    'kiwifruit',
    'kumquat',
    'lemon',
    'lime',
    'loganberry',
    'loquat',
    'longan',
    'lychee',
    'mango',
    'mangosteen',
    'marionberry',
    'melon',
    'cantaloupe',
    'galia',
    'honeydew',
    'watermelon',
    'miracle',
    'monstera',
    'mulberry',
    'nance',
    'nectarine',
    'orange',
    'blood',
    'clementine',
    'mandarine',
    'tangerine',
    'papaya',
    'passionfruit',
    'peach',
    'pear',
    'persimmon',
    'plantain',
    'plum',
    'prune',
    'pineapple',
    'pineberry',
    'plumcot',
    'pomegranate',
    'pomelo',
    'purple',
    'quince',
    'raspberry',
    'salmonberry',
    'rambutan',
    'redcurrant',
    'salal',
    'salak',
    'satsuma',
    'soursop',
    'star',
    'star',
    'strawberry',
    'surinam',
    'tamarillo',
    'tamarind',
    'tangelo',
    'tayberry',
    'ugli',
    'white',
    'white',
    'yuzu'
]
 productos.each do |fruta|
    puts fruta
 end
 puts ""
 puts productos.include? 'chico'
 puts productos.include? 'chillo'
productos [21] = 'cochinito'

 puts ""
 puts productos.index 'cochinito'
 puts productos.index 'hala'
 puts productos.index 'mangosteen'
 puts ""
 productos << 'zulu'
 puts ""
 puts productos.index 'zulu'
 coconut = productos [21]
 puts productos.index 'coconut'
 puts productos.first
 puts productos.last
